version: '2.4'

services:
  server:
    build: .
    container_name: example-server
    working_dir: /relay-graphql-monorepo/packages/server
    entrypoint: yarn start-dev
    ports:
      - '8080:8080'
